project:
  type: website
  #output-dir: docs

website:
  page-navigation: true
  back-to-top-navigation: true
  page-footer: 
    left: "Copyright 2025, Peter Ho" 
    right: 
      - icon: github
        href: https://github.com/
      - icon: twitter 
        href: https://twitter.com/ 

  title: "模式推估網站試做-Peter Ho"
  navbar:
    right:
      - href: index.qmd
        text: Home
      #- about.qmd
    search: true
    background: darkgreen
    pinned: true
  
  sidebar:
      style: "docked"
      #search: true
      contents:
        - text: "Introduction"
        - text: "CH1 "
          href: docs/web_CH1_Why_modeling.html
      background: none
      border: true

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
    mermaid:
      theme: neutral

editor: visual
