project:
  type: website
  output-dir: docs

highlight-style: pygments

website:
  page-navigation: true
  back-to-top-navigation: true
  page-footer: 
    border: true
    background: darkgreen
    left: "Copyright 2025, Peter Ho" 
    right: 
      - icon: github
        href: https://github.com/
      - icon: twitter 
        href: https://twitter.com/ 

  title: "OH模式推估-Peter Ho"
  navbar:
    left:
      - text: 首頁
        href: index.html
      - about.qmd
      - href: news
        text: 職安衛新知
      - href: modeling.qmd
        text: 模式推估
      - href: DRI.qmd
        text: 直讀式儀器與RPE
      - href: EA
        text: 暴露風險  
      - href: others.qmd
        text: 其他

    search: true
    background: darkgreen
    pinned: true
  
format:
  html:
    theme: 
      light: flatly
      dark: darkly    
    fontsize: 1em
    linestretch: 1
    css: styles.css
    toc: true
    mermaid:
      theme: neutral
    page-layout: full
    

editor: visual


