project:
  type: website
  output-dir: docs

highlight-style: pygments

website:
  page-navigation: true
  back-to-top-navigation: true
  page-footer: 
    border: true
    background: darkgreen
    left: "Copyright 2025, Peter Ho" 
    right: 
      - icon: github
        href: https://github.com/
      - icon: twitter 
        href: https://twitter.com/ 

  title: "OH模式推估-何明信"
#  navbar:
  sidebar:
    style: "docked"
    search: true
    contents:
#    left:
#      - text: 首頁
#        href: index.html
#      - text: About us
#        href: about.qmd
      - text: 職安衛訊息
        href: news.qmd
      - text: 115技師班
        href: 案例分析及演練(115技師班).qmd
        target: _blank                     
      - text: EAD_NIOSH
        href: EAD_NIOSH.qmd
        target: _blank
      - text: EAD_AIHA
        href: EAD.qmd
        target: _blank        
      - text: OEL與EA
        href: OEL.qmd
        target: _blank
      - text: MSA DRI
        href: MSA.qmd
        target: _blank
      - text: 直讀式儀器與RPE
        href: DRI.qmd
        target: _blank
    
#        href: noise_EA.qmd
#      - text: 噪音-高溫EA
#        href: EA.qmd
#      - text: HPD與噪音暴露風險
#        href: others.qmd
#      - text: 其他(安全議題)
      - text: 先期暴露風險評估技術手冊
        href: 先期暴露風險評估技術手冊.qmd
        target: _blank        

format:
  html:
    theme: 
      light: flatly
      dark: darkly    
    fontsize: 1em
    linestretch: 1
    css: styles.css
    toc: true
    mermaid:
      theme: neutral
    page-layout: full
    html-math-method: katex


editor: visual


