---
title: "有機溶劑中毒死亡職災"
---

::: {.callout-important appearance="simple"}
以下內容係用Google翻譯再修訂，正確性請參考資料來源(原文)
:::

一名工人因接觸有毒膠水死亡，維修公司被罰款 **1700萬台幣** (40萬英鎊)

資訊來源(原文)：[HSE 新聞稿](https://press.hse.gov.uk/2026/01/29/maintenance-company-fined-400000-after-worker-dies-from-toxic-glue-exposure/?utm_source=govdelivery&utm_medium=email&utm_campaign=press-channels-push&utm_term=exposure-1&utm_content=construction-25-feb-26)

2026年1月29日 新聞稿 一家房屋協會維修公司因一名員工吸入地板黏合劑產生的有毒蒸氣而死亡，被罰款 40 萬英鎊。

2020 年 12 月 9 日，38 歲的 Darren Nevill 在赫特福德郡霍德斯登的一處住宅物業中，為 Connect Property Services Limited 公司鋪設乙烯基浴室地板。

他的雇主提供了一種含有[***二氯甲烷（DCM）***]{.underline}的黏合劑，二氯甲烷是一種高揮發性溶劑。即使在室溫下，少量二氯甲烷也會釋放大量無色、低氣味的蒸氣。他在工作期間經常使用這種黏合劑。

在他去世當天，連接加壓膠罐的軟管損壞，導致大量膠水洩漏到通風不良的浴室。內維爾先生失去知覺並倒地不起。急救人員不得不強行進入浴室才能救出他。

英國健康與安全執行局 (HSE) 的一項調查發現，位於倫敦伊靈門戶區 Uxbridge 路 26-30 號的 Connect Property Services Limited 公司未能採取適當的預防措施，以確保在有更安全的替代品時，不使用對健康有害的物質。

英國健康與安全執行局 (HSE) 關於 二氯甲烷 (DCM) 的指導意見指出，應盡可能避免使用含二氯甲烷的產品，而應使用更安全、更合適的替代產品或方法。含二氯甲烷的產品只能在通風良好的區域使用，以防止蒸氣累積。通風不良的區域包括浴室、地下室、樓梯間和封閉式隔間。

該公司違反了 1974 年《工作場所健康與安全法》第 2(1) 條。 2026 年 1 月 26 日，在史蒂文尼奇地方法院，Connect Property Services Limited 被處以 40 萬英鎊的罰款，並被責令支付 9676.81 英鎊的訴訟費和 190 英鎊的附加費。

檢察官喬恩·麥克告訴法庭：「英國健康與安全執行局**`（HSE）的科學家計算得出，內維爾先生在2到13秒內就會達到法定15分鐘暴露限值(STEL)，而他去世時浴室內的最終濃度將是暴露限值的84.5倍。經檢測，內維爾先生體內的二氯甲烷濃度是致死濃度的三倍。」`**

HSE 的起訴是由 HSE 執法律師 Neenu Bains 和法律助理 Helen Jacob 提起的。

更多資訊

1.  英國健康與安全執行局(HSE) 是英國國家工作場所健康與安全監管機構。致力於保護人員和場所安全，並幫助每個人過著更安全、更健康的生活。
