---
title: "OSHA4480 鋰離子電池危害評估與控制 "
date: 2026-03-01
author: Peter Ho & River Ho.
---

美國OSHA官方資料 (Factsheet)

**主題：** 【工作場所鋰離子電池之危害分析與風險控制實務】

1.  **著重全生命週期管理：** 從化學危害、熱失控防護到 NFPA 855 儲能安全標準的整合應用

2.  **著重工程與管理控制：** 探討源頭安全設計（Safety by Design）與緊急應變建構

3.  **法規與標準：** 跨越 OSHA 規範與國際產業標準的安全與健康管理系統（SHMS）

#### **「危害分析」** 

鋰電池生命週期（包含製造、安裝、儲能與回收）的潛在風險包含了化學毒理學領域（如電解液遇水反應生成劇毒氟化氫）、物理與熱力學領域（因內部短路或極端溫度引發的熱失控連鎖反應），以及電氣危害。提醒職安衛人員必須擴大視角，從跨學科的角度來進行風險評估。

1.  **「系統化風險控制」的防護思維：** 現代職業衛生管理強調主動性與系統性。這文件提倡防護措施必須依循「危害控制層級（Hierarchy of Controls）」來建構。對雇主而言，不僅仰賴末端的個人防護裝備（PPE），更必須從最上游的「源頭安全設計（Safety by Design）」（如主動替換危害較低的技術）著手，並結合工程控制（如局部排氣通風、自動化隔離）以及成熟的安全與健康管理系統（SHMS），建構全面性防護網策略。

2.  **「實務」與標準整合：** 這份 OSHA 資訊為缺乏單一職安衛專屬標準的鋰電池領域提供一套整合性的實務指引。不僅點出雇主需遵守《職業安全與健康法》的一般責任條款，更廣泛引介了 NFPA 855（固定式儲能系統安裝標準）、IEC、UL 以及 ISO 45001 等國際共識標準作為輔助。對於工程人員與職安衛人員在編寫緊急應變計畫（EAP）、規劃勞工 危害通識教育訓練的實際執行需求。

OSHA資料網址：[Lithium-ion Battery Safety OSHA4480](www.osha.gov/sites/default/files/publications/OSHA4480.pdf)

消防與PPE可諮詢[MSA專業公司代表](https://peter7336959.github.io/EA/MSA.html)
